name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          sed -i '/dist/d' .gitignore
          git switch -c build
          git add -A
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Deploy: $GITHUB_SHA"

          git push origin build -f

